logging:
  level:
    spring:
      datasource: debug

server:
  servlet:
    context-path: /app
  port: 8080

spring:
  datasource:
    url: ${db.jdbc.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      auto-commit: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        format_sql: true
        generate_statistics: false
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

authentication:
  auth:
    tokenSecret: secret
    tokenExpirationMsec: 3600000 #1 hour
    refreshTokenExpirationMsec: 7776000000 #90 days
    accessTokenCookieName: accessToken
    refreshTokenCookieName: refreshToken
